#!/bin/bash
#SBATCH -J test_file                     	# Job name
#SBATCH -o test_file_%j.out              	# output file (%j expands to jobID)
#SBATCH -e test_file_%j.err              	# error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                  	# Request status by email
#SBATCH --mail-user=ep432@cornell.edu.   	# Email address to send results to.
#SBATCH -N 1                             	# Total number of nodes requested
#SBATCH -n 1                             	# Total number of cores requested
#SBATCH --get-user-env                   	# retrieve the users login environment
#SBATCH --mem=2000                       	# server memory requested (per node)
#SBATCH -t 2:00:00                       	# Time limit (hh:mm:ss)
#SBATCH --partition=ju         	# Request partition. If you want to submit to another partition (eg, default_partition) so you have access to all faculty computers, not just ours, change this argument!
#SBATCH --gres=gpu:1              	# Type/number of GPUs needed
python test_script.py 