#!/bin/bash
#SBATCH -J all      	# Job name
#SBATCH -o ./output/vlm_%j.out              	# output file (%j expands to jobID)
#SBATCH -e ./output/vlm_%j.err              	# error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                  	# Request status by email
#SBATCH --mail-user=mb2554@cornell.edu  	# Email address to send results to.
#SBATCH -N 1                             	# Total number of nodes requested
#SBATCH -n 8                             	# Total number of cores requested
#SBATCH --get-user-env                   	# retrieve the users login environment
#SBATCH --mem=64gb                   	# server memory requested (per node)
#SBATCH -t 70:00:00                       	# Time limit (hh:mm:ss)
#SBATCH --gres=gpu:1              	# Type/number of GPUs needed
#SBATCH --partition=gpu



python vlm_reactions_hf.py --video-folder "../../../../data/final_cut_videos/" --model "llava-hf/llava-v1.6-vicuna-7b-hf" --output-csv "./results/results_llava16vicuna.csv"
